---
#Allgemeine Einstellungen

#Commands & Funktionen
AntiXray: false
BoosterCommand: false
StarterKit: true
#ItemDisplay
inames: false #aktiviere/deaktiviere die ItemNamen

#Blitze beim Join
blitze: false #aktiviere/deaktiviere Blitze beim Joinen des Servers
sound: true #aktiviere/deaktiviere den Donner

#NetzwerkName
networkname: "CoreV5" #schreibe hier dein servername oder was frag mich rein...

#EconomySystem
DefaultMoney: 1000

#Weitere Einstellungen
defaultspawn: true
rejoinallowed: true #möchtest du das die Spieler automatich rejoinen?
rejoinserverip: 127.0.0.1
rejoinserverport: 19132
maxhomes: 10 #Setze ein Limit für Homes
collision: true #aktiviere/deaktiviere collision/schubsen
serverversion: pocketmine #nutze altay oder pocketmine um zwichen den verschiedenen versionen zu wechseln
keepinventory: false #setze auf true um dein Inventar zu Behalten
PingLimit: 300 #Setze das Maximale Pinglimit ein

#LiftSystem
helferprivatliftuse: true
helperprivateLift: true
checkFloor: true

#Statstext
statstext: false
X: 0
Y: 0
Z: 0
level: world
...